// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// AIPW_agreg_cpp
Rcpp::List AIPW_agreg_cpp(int maxiter, NumericVector start, NumericVector tstop, IntegerVector event, NumericMatrix covar, IntegerVector eventid, IntegerVector id, NumericVector offset, IntegerVector strata, IntegerVector sort1, IntegerVector sort2, IntegerMatrix marker, IntegerVector R, NumericMatrix pR, List dpR, IntegerMatrix total_R, List marker_r, IntegerVector whereX, IntegerVector whereW, NumericVector gamma, NumericMatrix comb_y, int nvar, int n_marker, int nR, int ngamma, int nalp, double eps, double toler, bool second_cont_bl, bool second_cont_rr, NumericVector init_beta);
RcppExport SEXP _AIPWsubtype_AIPW_agreg_cpp(SEXP maxiterSEXP, SEXP startSEXP, SEXP tstopSEXP, SEXP eventSEXP, SEXP covarSEXP, SEXP eventidSEXP, SEXP idSEXP, SEXP offsetSEXP, SEXP strataSEXP, SEXP sort1SEXP, SEXP sort2SEXP, SEXP markerSEXP, SEXP RSEXP, SEXP pRSEXP, SEXP dpRSEXP, SEXP total_RSEXP, SEXP marker_rSEXP, SEXP whereXSEXP, SEXP whereWSEXP, SEXP gammaSEXP, SEXP comb_ySEXP, SEXP nvarSEXP, SEXP n_markerSEXP, SEXP nRSEXP, SEXP ngammaSEXP, SEXP nalpSEXP, SEXP epsSEXP, SEXP tolerSEXP, SEXP second_cont_blSEXP, SEXP second_cont_rrSEXP, SEXP init_betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type start(startSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tstop(tstopSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type event(eventSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type covar(covarSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type eventid(eventidSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type id(idSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type strata(strataSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type sort1(sort1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type sort2(sort2SEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type marker(markerSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type R(RSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pR(pRSEXP);
    Rcpp::traits::input_parameter< List >::type dpR(dpRSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type total_R(total_RSEXP);
    Rcpp::traits::input_parameter< List >::type marker_r(marker_rSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type whereX(whereXSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type whereW(whereWSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type comb_y(comb_ySEXP);
    Rcpp::traits::input_parameter< int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< int >::type n_marker(n_markerSEXP);
    Rcpp::traits::input_parameter< int >::type nR(nRSEXP);
    Rcpp::traits::input_parameter< int >::type ngamma(ngammaSEXP);
    Rcpp::traits::input_parameter< int >::type nalp(nalpSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< double >::type toler(tolerSEXP);
    Rcpp::traits::input_parameter< bool >::type second_cont_bl(second_cont_blSEXP);
    Rcpp::traits::input_parameter< bool >::type second_cont_rr(second_cont_rrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type init_beta(init_betaSEXP);
    rcpp_result_gen = Rcpp::wrap(AIPW_agreg_cpp(maxiter, start, tstop, event, covar, eventid, id, offset, strata, sort1, sort2, marker, R, pR, dpR, total_R, marker_r, whereX, whereW, gamma, comb_y, nvar, n_marker, nR, ngamma, nalp, eps, toler, second_cont_bl, second_cont_rr, init_beta));
    return rcpp_result_gen;
END_RCPP
}
// AIPW_agscore_cpp
Rcpp::NumericMatrix AIPW_agscore_cpp(NumericVector start, NumericVector stop, IntegerVector event, NumericMatrix covar, IntegerVector eventid, IntegerVector id, NumericVector score, IntegerVector strata, IntegerMatrix marker, IntegerVector R, NumericMatrix pR, IntegerMatrix total_R, List marker_r, IntegerVector whereX, IntegerVector whereW, NumericVector gamma, NumericMatrix comb_y, int nvar, int n_marker, int nR, int ngamma, int nalp, bool second_cont_bl, bool second_cont_rr);
RcppExport SEXP _AIPWsubtype_AIPW_agscore_cpp(SEXP startSEXP, SEXP stopSEXP, SEXP eventSEXP, SEXP covarSEXP, SEXP eventidSEXP, SEXP idSEXP, SEXP scoreSEXP, SEXP strataSEXP, SEXP markerSEXP, SEXP RSEXP, SEXP pRSEXP, SEXP total_RSEXP, SEXP marker_rSEXP, SEXP whereXSEXP, SEXP whereWSEXP, SEXP gammaSEXP, SEXP comb_ySEXP, SEXP nvarSEXP, SEXP n_markerSEXP, SEXP nRSEXP, SEXP ngammaSEXP, SEXP nalpSEXP, SEXP second_cont_blSEXP, SEXP second_cont_rrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type start(startSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type stop(stopSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type event(eventSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type covar(covarSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type eventid(eventidSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type id(idSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type score(scoreSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type strata(strataSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type marker(markerSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type R(RSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pR(pRSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type total_R(total_RSEXP);
    Rcpp::traits::input_parameter< List >::type marker_r(marker_rSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type whereX(whereXSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type whereW(whereWSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type comb_y(comb_ySEXP);
    Rcpp::traits::input_parameter< int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< int >::type n_marker(n_markerSEXP);
    Rcpp::traits::input_parameter< int >::type nR(nRSEXP);
    Rcpp::traits::input_parameter< int >::type ngamma(ngammaSEXP);
    Rcpp::traits::input_parameter< int >::type nalp(nalpSEXP);
    Rcpp::traits::input_parameter< bool >::type second_cont_bl(second_cont_blSEXP);
    Rcpp::traits::input_parameter< bool >::type second_cont_rr(second_cont_rrSEXP);
    rcpp_result_gen = Rcpp::wrap(AIPW_agscore_cpp(start, stop, event, covar, eventid, id, score, strata, marker, R, pR, total_R, marker_r, whereX, whereW, gamma, comb_y, nvar, n_marker, nR, ngamma, nalp, second_cont_bl, second_cont_rr));
    return rcpp_result_gen;
END_RCPP
}
// AIPW_coxfit_cpp
Rcpp::List AIPW_coxfit_cpp(int maxiter, NumericVector time, IntegerVector status, NumericMatrix covar, IntegerVector eventid, IntegerVector id, NumericVector offset, IntegerVector strata, IntegerMatrix marker, IntegerVector R, NumericMatrix pR, List dpR, IntegerMatrix total_R, List marker_r, IntegerVector whereX, IntegerVector whereW, NumericVector gamma, NumericMatrix comb_y, int nvar, int n_marker, int nR, int ngamma, int nalp, double eps, double toler, bool second_cont_bl, bool second_cont_rr, NumericVector init_beta);
RcppExport SEXP _AIPWsubtype_AIPW_coxfit_cpp(SEXP maxiterSEXP, SEXP timeSEXP, SEXP statusSEXP, SEXP covarSEXP, SEXP eventidSEXP, SEXP idSEXP, SEXP offsetSEXP, SEXP strataSEXP, SEXP markerSEXP, SEXP RSEXP, SEXP pRSEXP, SEXP dpRSEXP, SEXP total_RSEXP, SEXP marker_rSEXP, SEXP whereXSEXP, SEXP whereWSEXP, SEXP gammaSEXP, SEXP comb_ySEXP, SEXP nvarSEXP, SEXP n_markerSEXP, SEXP nRSEXP, SEXP ngammaSEXP, SEXP nalpSEXP, SEXP epsSEXP, SEXP tolerSEXP, SEXP second_cont_blSEXP, SEXP second_cont_rrSEXP, SEXP init_betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type status(statusSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type covar(covarSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type eventid(eventidSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type id(idSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type strata(strataSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type marker(markerSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type R(RSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pR(pRSEXP);
    Rcpp::traits::input_parameter< List >::type dpR(dpRSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type total_R(total_RSEXP);
    Rcpp::traits::input_parameter< List >::type marker_r(marker_rSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type whereX(whereXSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type whereW(whereWSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type comb_y(comb_ySEXP);
    Rcpp::traits::input_parameter< int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< int >::type n_marker(n_markerSEXP);
    Rcpp::traits::input_parameter< int >::type nR(nRSEXP);
    Rcpp::traits::input_parameter< int >::type ngamma(ngammaSEXP);
    Rcpp::traits::input_parameter< int >::type nalp(nalpSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< double >::type toler(tolerSEXP);
    Rcpp::traits::input_parameter< bool >::type second_cont_bl(second_cont_blSEXP);
    Rcpp::traits::input_parameter< bool >::type second_cont_rr(second_cont_rrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type init_beta(init_betaSEXP);
    rcpp_result_gen = Rcpp::wrap(AIPW_coxfit_cpp(maxiter, time, status, covar, eventid, id, offset, strata, marker, R, pR, dpR, total_R, marker_r, whereX, whereW, gamma, comb_y, nvar, n_marker, nR, ngamma, nalp, eps, toler, second_cont_bl, second_cont_rr, init_beta));
    return rcpp_result_gen;
END_RCPP
}
// AIPW_coxscore_cpp
Rcpp::NumericMatrix AIPW_coxscore_cpp(NumericVector time, NumericVector status, NumericMatrix covar, IntegerVector eventid, IntegerVector id, NumericVector score, IntegerVector strata, IntegerMatrix marker, IntegerVector R, NumericMatrix pR, IntegerMatrix total_R, List marker_r, IntegerVector whereX, IntegerVector whereW, NumericVector gamma, NumericMatrix comb_y, int nvar, int n_marker, int nR, int ngamma, int nalp, bool second_cont_bl, bool second_cont_rr);
RcppExport SEXP _AIPWsubtype_AIPW_coxscore_cpp(SEXP timeSEXP, SEXP statusSEXP, SEXP covarSEXP, SEXP eventidSEXP, SEXP idSEXP, SEXP scoreSEXP, SEXP strataSEXP, SEXP markerSEXP, SEXP RSEXP, SEXP pRSEXP, SEXP total_RSEXP, SEXP marker_rSEXP, SEXP whereXSEXP, SEXP whereWSEXP, SEXP gammaSEXP, SEXP comb_ySEXP, SEXP nvarSEXP, SEXP n_markerSEXP, SEXP nRSEXP, SEXP ngammaSEXP, SEXP nalpSEXP, SEXP second_cont_blSEXP, SEXP second_cont_rrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type status(statusSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type covar(covarSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type eventid(eventidSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type id(idSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type score(scoreSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type strata(strataSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type marker(markerSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type R(RSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pR(pRSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type total_R(total_RSEXP);
    Rcpp::traits::input_parameter< List >::type marker_r(marker_rSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type whereX(whereXSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type whereW(whereWSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type comb_y(comb_ySEXP);
    Rcpp::traits::input_parameter< int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< int >::type n_marker(n_markerSEXP);
    Rcpp::traits::input_parameter< int >::type nR(nRSEXP);
    Rcpp::traits::input_parameter< int >::type ngamma(ngammaSEXP);
    Rcpp::traits::input_parameter< int >::type nalp(nalpSEXP);
    Rcpp::traits::input_parameter< bool >::type second_cont_bl(second_cont_blSEXP);
    Rcpp::traits::input_parameter< bool >::type second_cont_rr(second_cont_rrSEXP);
    rcpp_result_gen = Rcpp::wrap(AIPW_coxscore_cpp(time, status, covar, eventid, id, score, strata, marker, R, pR, total_R, marker_r, whereX, whereW, gamma, comb_y, nvar, n_marker, nR, ngamma, nalp, second_cont_bl, second_cont_rr));
    return rcpp_result_gen;
END_RCPP
}
// IPW_ithealp_ag
NumericMatrix IPW_ithealp_ag(NumericVector start, NumericVector stop, IntegerVector event, NumericVector eta, IntegerVector strata, IntegerVector sort1, IntegerVector sort2, NumericMatrix covar, NumericMatrix dpi, NumericVector weights, int nused, int nvar, int nalp);
RcppExport SEXP _AIPWsubtype_IPW_ithealp_ag(SEXP startSEXP, SEXP stopSEXP, SEXP eventSEXP, SEXP etaSEXP, SEXP strataSEXP, SEXP sort1SEXP, SEXP sort2SEXP, SEXP covarSEXP, SEXP dpiSEXP, SEXP weightsSEXP, SEXP nusedSEXP, SEXP nvarSEXP, SEXP nalpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type start(startSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type stop(stopSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type event(eventSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type strata(strataSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type sort1(sort1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type sort2(sort2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type covar(covarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dpi(dpiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type nused(nusedSEXP);
    Rcpp::traits::input_parameter< int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< int >::type nalp(nalpSEXP);
    rcpp_result_gen = Rcpp::wrap(IPW_ithealp_ag(start, stop, event, eta, strata, sort1, sort2, covar, dpi, weights, nused, nvar, nalp));
    return rcpp_result_gen;
END_RCPP
}
// IPW_ithealp_cox
NumericMatrix IPW_ithealp_cox(NumericVector time, IntegerVector status, NumericVector lp, IntegerVector strata, NumericMatrix covar, NumericMatrix dpi, NumericVector weights, int nused, int nvar, int nalp);
RcppExport SEXP _AIPWsubtype_IPW_ithealp_cox(SEXP timeSEXP, SEXP statusSEXP, SEXP lpSEXP, SEXP strataSEXP, SEXP covarSEXP, SEXP dpiSEXP, SEXP weightsSEXP, SEXP nusedSEXP, SEXP nvarSEXP, SEXP nalpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type status(statusSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lp(lpSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type strata(strataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type covar(covarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dpi(dpiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type nused(nusedSEXP);
    Rcpp::traits::input_parameter< int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< int >::type nalp(nalpSEXP);
    rcpp_result_gen = Rcpp::wrap(IPW_ithealp_cox(time, status, lp, strata, covar, dpi, weights, nused, nvar, nalp));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_AIPWsubtype_AIPW_agreg_cpp", (DL_FUNC) &_AIPWsubtype_AIPW_agreg_cpp, 31},
    {"_AIPWsubtype_AIPW_agscore_cpp", (DL_FUNC) &_AIPWsubtype_AIPW_agscore_cpp, 24},
    {"_AIPWsubtype_AIPW_coxfit_cpp", (DL_FUNC) &_AIPWsubtype_AIPW_coxfit_cpp, 28},
    {"_AIPWsubtype_AIPW_coxscore_cpp", (DL_FUNC) &_AIPWsubtype_AIPW_coxscore_cpp, 23},
    {"_AIPWsubtype_IPW_ithealp_ag", (DL_FUNC) &_AIPWsubtype_IPW_ithealp_ag, 13},
    {"_AIPWsubtype_IPW_ithealp_cox", (DL_FUNC) &_AIPWsubtype_IPW_ithealp_cox, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_AIPWsubtype(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
