# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AIPW_coxscore_cpp <- function(time, status, covar, eventid, id, score, strata, marker, R, pR, total_R, marker_r, whereX, whereW, gamma, comb_y, nvar, n_marker, nR, ngamma, nalp, second_cont_bl, second_cont_rr) {
    .Call(`_AIPWsubtype_AIPW_coxscore_cpp`, time, status, covar, eventid, id, score, strata, marker, R, pR, total_R, marker_r, whereX, whereW, gamma, comb_y, nvar, n_marker, nR, ngamma, nalp, second_cont_bl, second_cont_rr)
}

