# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AIPW_agreg_cpp <- function(maxiter, start, tstop, event, covar, eventid, id, offset, strata, sort1, sort2, marker, R, pR, dpR, total_R, marker_r, whereX, whereW, gamma, comb_y, nvar, n_marker, nR, ngamma, nalp, eps, toler, second_cont_bl, second_cont_rr, init_beta) {
    .Call(`_AIPWsubtype_AIPW_agreg_cpp`, maxiter, start, tstop, event, covar, eventid, id, offset, strata, sort1, sort2, marker, R, pR, dpR, total_R, marker_r, whereX, whereW, gamma, comb_y, nvar, n_marker, nR, ngamma, nalp, eps, toler, second_cont_bl, second_cont_rr, init_beta)
}

AIPW_agscore_cpp <- function(start, stop, event, covar, eventid, id, score, strata, marker, R, pR, total_R, marker_r, whereX, whereW, gamma, comb_y, nvar, n_marker, nR, ngamma, nalp, second_cont_bl, second_cont_rr) {
    .Call(`_AIPWsubtype_AIPW_agscore_cpp`, start, stop, event, covar, eventid, id, score, strata, marker, R, pR, total_R, marker_r, whereX, whereW, gamma, comb_y, nvar, n_marker, nR, ngamma, nalp, second_cont_bl, second_cont_rr)
}

AIPW_coxfit_cpp <- function(maxiter, time, status, covar, eventid, id, offset, strata, marker, R, pR, dpR, total_R, marker_r, whereX, whereW, gamma, comb_y, nvar, n_marker, nR, ngamma, nalp, eps, toler, second_cont_bl, second_cont_rr, init_beta) {
    .Call(`_AIPWsubtype_AIPW_coxfit_cpp`, maxiter, time, status, covar, eventid, id, offset, strata, marker, R, pR, dpR, total_R, marker_r, whereX, whereW, gamma, comb_y, nvar, n_marker, nR, ngamma, nalp, eps, toler, second_cont_bl, second_cont_rr, init_beta)
}

AIPW_coxscore_cpp <- function(time, status, covar, eventid, id, score, strata, marker, R, pR, total_R, marker_r, whereX, whereW, gamma, comb_y, nvar, n_marker, nR, ngamma, nalp, second_cont_bl, second_cont_rr) {
    .Call(`_AIPWsubtype_AIPW_coxscore_cpp`, time, status, covar, eventid, id, score, strata, marker, R, pR, total_R, marker_r, whereX, whereW, gamma, comb_y, nvar, n_marker, nR, ngamma, nalp, second_cont_bl, second_cont_rr)
}

IPW_ithealp_ag <- function(start, stop, event, eta, strata, sort1, sort2, covar, dpi, weights, nused, nvar, nalp) {
    .Call(`_AIPWsubtype_IPW_ithealp_ag`, start, stop, event, eta, strata, sort1, sort2, covar, dpi, weights, nused, nvar, nalp)
}

IPW_ithealp_cox <- function(time, status, lp, strata, covar, dpi, weights, nused, nvar, nalp) {
    .Call(`_AIPWsubtype_IPW_ithealp_cox`, time, status, lp, strata, covar, dpi, weights, nused, nvar, nalp)
}

